version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    volumes:
      - .:/app
    command: python app.py
    
  # Optional: Add Redis for caching/session storage
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  
  # Optional: Add nginx for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - web

networks:
  default:
    name: hotel-booking-predictor
