[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python extract_model.py']

[start]
cmd = 'gunicorn --workers=1 --timeout=120 --bind=0.0.0.0:$PORT app:app'
