[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = [
    'echo "Building ML model..."',
    'python extract_model.py',
    'echo "Model build complete"'
]

[start]
cmd = 'python start.py'
