services:
  - type: web
    name: hotel-booking-predictor
    runtime: python
    buildCommand: "pip install -r requirements.txt && python extract_model.py"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
